# Generated by Django 2.2.4 on 2019-10-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191001_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
