# Generated by Django 2.2.4 on 2019-10-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_modelpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
