# Generated by Django 2.2.4 on 2019-10-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191001_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpost',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
